
** Lines to export results to Line18 of the excel file

putexcel E18=matrix(cp_all_percent)
putexcel F18=matrix(cp_all_se)
putexcel G18=matrix(cp_all_ll)
putexcel H18=matrix(cp_all_ul)
putexcel I18=matrix(mcp_all_percent)
putexcel J18=matrix(mcp_all_se)
putexcel K18=matrix(mcp_all_ll)
putexcel L18=matrix(mcp_all_ul)
putexcel M18=matrix(unmettot_all_percent)
putexcel N18=matrix(unmettot_all_se)
putexcel O18=matrix(unmettot_all_ll)
putexcel P18=matrix(unmettot_all_ul)
putexcel R18=matrix(cp_mar_percent)
putexcel S18=matrix(cp_mar_se)
putexcel T18=matrix(cp_mar_ll)
putexcel U18=matrix(cp_mar_ul)
putexcel V18=matrix(mcp_mar_percent)
putexcel W18=matrix(mcp_mar_se)
putexcel X18=matrix(mcp_mar_ll)
putexcel Y18=matrix(mcp_mar_ul)
putexcel Z18=matrix(unmettot_mar_percent)
putexcel AA18=matrix(unmettot_mar_se)
putexcel AB18=matrix(unmettot_mar_ll)
putexcel AC18=matrix(unmettot_mar_ul)
