
** Lines to export results to Line20 of the excel file

putexcel E20=matrix(cp_all_percent)
putexcel F20=matrix(cp_all_se)
putexcel G20=matrix(cp_all_ll)
putexcel H20=matrix(cp_all_ul)
putexcel I20=matrix(mcp_all_percent)
putexcel J20=matrix(mcp_all_se)
putexcel K20=matrix(mcp_all_ll)
putexcel L20=matrix(mcp_all_ul)
putexcel M20=matrix(unmettot_all_percent)
putexcel N20=matrix(unmettot_all_se)
putexcel O20=matrix(unmettot_all_ll)
putexcel P20=matrix(unmettot_all_ul)
putexcel R20=matrix(cp_mar_percent)
putexcel S20=matrix(cp_mar_se)
putexcel T20=matrix(cp_mar_ll)
putexcel U20=matrix(cp_mar_ul)
putexcel V20=matrix(mcp_mar_percent)
putexcel W20=matrix(mcp_mar_se)
putexcel X20=matrix(mcp_mar_ll)
putexcel Y20=matrix(mcp_mar_ul)
putexcel Z20=matrix(unmettot_mar_percent)
putexcel AA20=matrix(unmettot_mar_se)
putexcel AB20=matrix(unmettot_mar_ll)
putexcel AC20=matrix(unmettot_mar_ul)
