
** Lines to export results to Line21 of the excel file

putexcel E21=matrix(cp_all_percent)
putexcel F21=matrix(cp_all_se)
putexcel G21=matrix(cp_all_ll)
putexcel H21=matrix(cp_all_ul)
putexcel I21=matrix(mcp_all_percent)
putexcel J21=matrix(mcp_all_se)
putexcel K21=matrix(mcp_all_ll)
putexcel L21=matrix(mcp_all_ul)
putexcel M21=matrix(unmettot_all_percent)
putexcel N21=matrix(unmettot_all_se)
putexcel O21=matrix(unmettot_all_ll)
putexcel P21=matrix(unmettot_all_ul)
putexcel R21=matrix(cp_mar_percent)
putexcel S21=matrix(cp_mar_se)
putexcel T21=matrix(cp_mar_ll)
putexcel U21=matrix(cp_mar_ul)
putexcel V21=matrix(mcp_mar_percent)
putexcel W21=matrix(mcp_mar_se)
putexcel X21=matrix(mcp_mar_ll)
putexcel Y21=matrix(mcp_mar_ul)
putexcel Z21=matrix(unmettot_mar_percent)
putexcel AA21=matrix(unmettot_mar_se)
putexcel AB21=matrix(unmettot_mar_ll)
putexcel AC21=matrix(unmettot_mar_ul)
