
** Lines to export results to Line10 of the excel file

putexcel E10=matrix(cp_all_percent)
putexcel F10=matrix(cp_all_se)
putexcel G10=matrix(cp_all_ll)
putexcel H10=matrix(cp_all_ul)
putexcel I10=matrix(mcp_all_percent)
putexcel J10=matrix(mcp_all_se)
putexcel K10=matrix(mcp_all_ll)
putexcel L10=matrix(mcp_all_ul)
putexcel M10=matrix(unmettot_all_percent)
putexcel N10=matrix(unmettot_all_se)
putexcel O10=matrix(unmettot_all_ll)
putexcel P10=matrix(unmettot_all_ul)
putexcel R10=matrix(cp_mar_percent)
putexcel S10=matrix(cp_mar_se)
putexcel T10=matrix(cp_mar_ll)
putexcel U10=matrix(cp_mar_ul)
putexcel V10=matrix(mcp_mar_percent)
putexcel W10=matrix(mcp_mar_se)
putexcel X10=matrix(mcp_mar_ll)
putexcel Y10=matrix(mcp_mar_ul)
putexcel Z10=matrix(unmettot_mar_percent)
putexcel AA10=matrix(unmettot_mar_se)
putexcel AB10=matrix(unmettot_mar_ll)
putexcel AC10=matrix(unmettot_mar_ul)
