
** Lines to export results to Line9 of the excel file

putexcel E9=matrix(cp_all_percent)
putexcel F9=matrix(cp_all_se)
putexcel G9=matrix(cp_all_ll)
putexcel H9=matrix(cp_all_ul)
putexcel I9=matrix(mcp_all_percent)
putexcel J9=matrix(mcp_all_se)
putexcel K9=matrix(mcp_all_ll)
putexcel L9=matrix(mcp_all_ul)
putexcel M9=matrix(unmettot_all_percent)
putexcel N9=matrix(unmettot_all_se)
putexcel O9=matrix(unmettot_all_ll)
putexcel P9=matrix(unmettot_all_ul)
putexcel R9=matrix(cp_mar_percent)
putexcel S9=matrix(cp_mar_se)
putexcel T9=matrix(cp_mar_ll)
putexcel U9=matrix(cp_mar_ul)
putexcel V9=matrix(mcp_mar_percent)
putexcel W9=matrix(mcp_mar_se)
putexcel X9=matrix(mcp_mar_ll)
putexcel Y9=matrix(mcp_mar_ul)
putexcel Z9=matrix(unmettot_mar_percent)
putexcel AA9=matrix(unmettot_mar_se)
putexcel AB9=matrix(unmettot_mar_ll)
putexcel AC9=matrix(unmettot_mar_ul)
