
** Lines to export results to Line11 of the excel file

putexcel E11=matrix(cp_all_percent)
putexcel F11=matrix(cp_all_se)
putexcel G11=matrix(cp_all_ll)
putexcel H11=matrix(cp_all_ul)
putexcel I11=matrix(mcp_all_percent)
putexcel J11=matrix(mcp_all_se)
putexcel K11=matrix(mcp_all_ll)
putexcel L11=matrix(mcp_all_ul)
putexcel M11=matrix(unmettot_all_percent)
putexcel N11=matrix(unmettot_all_se)
putexcel O11=matrix(unmettot_all_ll)
putexcel P11=matrix(unmettot_all_ul)
putexcel R11=matrix(cp_mar_percent)
putexcel S11=matrix(cp_mar_se)
putexcel T11=matrix(cp_mar_ll)
putexcel U11=matrix(cp_mar_ul)
putexcel V11=matrix(mcp_mar_percent)
putexcel W11=matrix(mcp_mar_se)
putexcel X11=matrix(mcp_mar_ll)
putexcel Y11=matrix(mcp_mar_ul)
putexcel Z11=matrix(unmettot_mar_percent)
putexcel AA11=matrix(unmettot_mar_se)
putexcel AB11=matrix(unmettot_mar_ll)
putexcel AC11=matrix(unmettot_mar_ul)
