
** Lines to export results to Line17 of the excel file

putexcel E17=matrix(cp_all_percent)
putexcel F17=matrix(cp_all_se)
putexcel G17=matrix(cp_all_ll)
putexcel H17=matrix(cp_all_ul)
putexcel I17=matrix(mcp_all_percent)
putexcel J17=matrix(mcp_all_se)
putexcel K17=matrix(mcp_all_ll)
putexcel L17=matrix(mcp_all_ul)
putexcel M17=matrix(unmettot_all_percent)
putexcel N17=matrix(unmettot_all_se)
putexcel O17=matrix(unmettot_all_ll)
putexcel P17=matrix(unmettot_all_ul)
putexcel R17=matrix(cp_mar_percent)
putexcel S17=matrix(cp_mar_se)
putexcel T17=matrix(cp_mar_ll)
putexcel U17=matrix(cp_mar_ul)
putexcel V17=matrix(mcp_mar_percent)
putexcel W17=matrix(mcp_mar_se)
putexcel X17=matrix(mcp_mar_ll)
putexcel Y17=matrix(mcp_mar_ul)
putexcel Z17=matrix(unmettot_mar_percent)
putexcel AA17=matrix(unmettot_mar_se)
putexcel AB17=matrix(unmettot_mar_ll)
putexcel AC17=matrix(unmettot_mar_ul)
