
** Lines to export results to Line8 of the excel file

putexcel E8=matrix(cp_all_percent)
putexcel F8=matrix(cp_all_se)
putexcel G8=matrix(cp_all_ll)
putexcel H8=matrix(cp_all_ul)
putexcel I8=matrix(mcp_all_percent)
putexcel J8=matrix(mcp_all_se)
putexcel K8=matrix(mcp_all_ll)
putexcel L8=matrix(mcp_all_ul)
putexcel M8=matrix(unmettot_all_percent)
putexcel N8=matrix(unmettot_all_se)
putexcel O8=matrix(unmettot_all_ll)
putexcel P8=matrix(unmettot_all_ul)
putexcel R8=matrix(cp_mar_percent)
putexcel S8=matrix(cp_mar_se)
putexcel T8=matrix(cp_mar_ll)
putexcel U8=matrix(cp_mar_ul)
putexcel V8=matrix(mcp_mar_percent)
putexcel W8=matrix(mcp_mar_se)
putexcel X8=matrix(mcp_mar_ll)
putexcel Y8=matrix(mcp_mar_ul)
putexcel Z8=matrix(unmettot_mar_percent)
putexcel AA8=matrix(unmettot_mar_se)
putexcel AB8=matrix(unmettot_mar_ll)
putexcel AC8=matrix(unmettot_mar_ul)
