
** Lines to export results to Line12 of the excel file

putexcel E12=matrix(cp_all_percent)
putexcel F12=matrix(cp_all_se)
putexcel G12=matrix(cp_all_ll)
putexcel H12=matrix(cp_all_ul)
putexcel I12=matrix(mcp_all_percent)
putexcel J12=matrix(mcp_all_se)
putexcel K12=matrix(mcp_all_ll)
putexcel L12=matrix(mcp_all_ul)
putexcel M12=matrix(unmettot_all_percent)
putexcel N12=matrix(unmettot_all_se)
putexcel O12=matrix(unmettot_all_ll)
putexcel P12=matrix(unmettot_all_ul)
putexcel R12=matrix(cp_mar_percent)
putexcel S12=matrix(cp_mar_se)
putexcel T12=matrix(cp_mar_ll)
putexcel U12=matrix(cp_mar_ul)
putexcel V12=matrix(mcp_mar_percent)
putexcel W12=matrix(mcp_mar_se)
putexcel X12=matrix(mcp_mar_ll)
putexcel Y12=matrix(mcp_mar_ul)
putexcel Z12=matrix(unmettot_mar_percent)
putexcel AA12=matrix(unmettot_mar_se)
putexcel AB12=matrix(unmettot_mar_ll)
putexcel AC12=matrix(unmettot_mar_ul)
