
** Lines to export results to Line19 of the excel file

putexcel E19=matrix(cp_all_percent)
putexcel F19=matrix(cp_all_se)
putexcel G19=matrix(cp_all_ll)
putexcel H19=matrix(cp_all_ul)
putexcel I19=matrix(mcp_all_percent)
putexcel J19=matrix(mcp_all_se)
putexcel K19=matrix(mcp_all_ll)
putexcel L19=matrix(mcp_all_ul)
putexcel M19=matrix(unmettot_all_percent)
putexcel N19=matrix(unmettot_all_se)
putexcel O19=matrix(unmettot_all_ll)
putexcel P19=matrix(unmettot_all_ul)
putexcel R19=matrix(cp_mar_percent)
putexcel S19=matrix(cp_mar_se)
putexcel T19=matrix(cp_mar_ll)
putexcel U19=matrix(cp_mar_ul)
putexcel V19=matrix(mcp_mar_percent)
putexcel W19=matrix(mcp_mar_se)
putexcel X19=matrix(mcp_mar_ll)
putexcel Y19=matrix(mcp_mar_ul)
putexcel Z19=matrix(unmettot_mar_percent)
putexcel AA19=matrix(unmettot_mar_se)
putexcel AB19=matrix(unmettot_mar_ll)
putexcel AC19=matrix(unmettot_mar_ul)
