
** Lines to export results to Line13 of the excel file

putexcel E13=matrix(cp_all_percent)
putexcel F13=matrix(cp_all_se)
putexcel G13=matrix(cp_all_ll)
putexcel H13=matrix(cp_all_ul)
putexcel I13=matrix(mcp_all_percent)
putexcel J13=matrix(mcp_all_se)
putexcel K13=matrix(mcp_all_ll)
putexcel L13=matrix(mcp_all_ul)
putexcel M13=matrix(unmettot_all_percent)
putexcel N13=matrix(unmettot_all_se)
putexcel O13=matrix(unmettot_all_ll)
putexcel P13=matrix(unmettot_all_ul)
putexcel R13=matrix(cp_mar_percent)
putexcel S13=matrix(cp_mar_se)
putexcel T13=matrix(cp_mar_ll)
putexcel U13=matrix(cp_mar_ul)
putexcel V13=matrix(mcp_mar_percent)
putexcel W13=matrix(mcp_mar_se)
putexcel X13=matrix(mcp_mar_ll)
putexcel Y13=matrix(mcp_mar_ul)
putexcel Z13=matrix(unmettot_mar_percent)
putexcel AA13=matrix(unmettot_mar_se)
putexcel AB13=matrix(unmettot_mar_ll)
putexcel AC13=matrix(unmettot_mar_ul)
